export const doctorsCardsData = [
  {
    id: 1,
    name: "Dr. Sarah Johnson",
    specialty: "Cardiologist",
    imageUrl: "https://randomuser.me/api/portraits/women/45.jpg",
    hospital: "Central Medical Center",
    rating: 4.9,
    reviews: 124,
    bio: "Dr. Sarah Johnson is a board-certified cardiologist with over 12 years of experience in treating cardiovascular diseases. She completed her medical training at Harvard Medical School and residency at Massachusetts General Hospital.",
    profileLink: "/appointments?doctor=1",
  },
  {
    id: 2,
    name: "Dr. Michael Chen",
    specialty: "Dermatologist",
    imageUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    hospital: "Westside Hospital",
    rating: 4.7,
    reviews: 98,
    bio: "Dr. Michael Chen specializes in medical, surgical, and cosmetic dermatology. He has expertise in treating skin conditions like acne, eczema, psoriasis, and skin cancer.",
    profileLink: "/appointments?doctor=2",
  },
  {
    id: 3,
    name: "Dr. Emily Rodriguez",
    specialty: "Neurology",
    imageUrl: "https://randomuser.me/api/portraits/women/63.jpg",
    hospital: "Metropolitan Medical Center",
    rating: 4.8,
    reviews: 156,
    bio: "Dr. Emily Rodriguez is a neurologist with expertise in headache disorders, multiple sclerosis, and neurodegenerative diseases. She is dedicated to providing compassionate care for patients with complex neurological conditions.",
    profileLink: "/appointments?doctor=3",
  },
  {
    id: 4,
    name: "Dr. James Wilson",
    specialty: "Orthopedics",
    imageUrl: "https://randomuser.me/api/portraits/men/46.jpg",
    hospital: "Central Medical Center",
    rating: 4.6,
    reviews: 87,
    bio: "Dr. James Wilson is an orthopedic surgeon specializing in sports medicine, joint replacement, and trauma. With 20 years of experience, he has helped thousands of patients recover from orthopedic injuries and conditions.",
    profileLink: "/appointments?doctor=4",
  },
  {
    id: 5,
    name: "Dr. Lisa Kim",
    specialty: "Pediatrics",
    imageUrl: "https://randomuser.me/api/portraits/women/69.jpg",
    hospital: "Children's Health Center",
    rating: 4.9,
    reviews: 142,
    bio: "Dr. Lisa Kim is a dedicated pediatrician who provides comprehensive healthcare for children from birth through adolescence. She is known for her gentle approach and ability to connect with young patients.",
    profileLink: "/appointments?doctor=5",
  },
  {
    id: 6,
    name: "Dr. Robert Taylor",
    specialty: "Psychiatry",
    imageUrl: "https://randomuser.me/api/portraits/men/79.jpg",
    hospital: "Behavioral Health Institute",
    rating: 4.8,
    reviews: 73,
    bio: "Dr. Robert Taylor is a psychiatrist specializing in mood disorders, anxiety, and PTSD. He takes a holistic approach to mental health, combining medication management with psychotherapy when appropriate.",
    profileLink: "/appointments?doctor=6",
  },
];
